mechawrench/wificom-lib

- CHANGELOG.md
- code.py
- lib/wificom/mqtt/platform_io.py
Legendz battles are partly working.
* Use dmcomm-python RTB version
* Fix realtime battle topic for different users
* Attempt Legendz realtime battles
> Add realtime battle support for PenX

- CHANGELOG.md
- code.py
- lib/wificom/mqtt/platform_io.py
This PR brings in realtime battle support for WiFiCom on the Pendulum X Digimon device
CoAuthored by @dmcomm @mechawrench
> Feature/realtime battles - PenX Support

- code.py
- lib/wificom/mqtt/platform_io.py
platform_io was really a module-level singleton
> Remove PlatformIO class

- lib/wificom/mqtt/minimqtt.py
Adds ACK publish for website sent commands
> Adds Ack for webapp sent commands

- .pylintrc
- CHANGELOG.md
- board_config.py
- code.py
- lib/wificom/hardware/pio_sound.py
- lib/wificom/hardware/ui.py
* Add sound output with various beeps for different menu actions
* UI object now exists even when there is no display
> Add sound output for menu actions

- .github/workflows/pylint.yml
- This should solve the issue with forks not running GitHub actions
- This should solve the issue with pull_requests from external not running GitHub actions
> GitHub workflow run on push, pull_request

- CHANGELOG.md
- README.md
- code.py
- config.py
- lib/wificom/sound.py
- lib/wificom/ui.py
#53
Wait until multi WiFi is just about ready.
> Add sound on/off option; digiroms.py->config.py

- CHANGELOG.md
- code.py
> Return to punchbag menu

- CHANGELOG.md
- code.py
- Audible beep for when a DigiROM is received via MQTT while on Wifi mode
> Digirom audio feedback

- .pylintrc
> Fix .pylintrc warnings

- .github/workflows/pylint.yml
- .pylintrc
- lib/wificom/main.py
We can update this now. I think `useless-suppression` is good, and the bug I was having was fixed.
No release notes.
> Pylint to 2.17.1, enable useless-suppression

- sources.json
- Updated dmcomm-python to v0.6.0 (basic Digimon Color support, DMOG fix)
> Update dmcomm-python to v0.6.0

- .github/workflows/merge-libs-compile-circuitpython-files.yml
- Upload artifacts to public S3 bucket, used with the install/update tool to install from a commit
> Add S3 Artifact uploads

- lib/wificom/main.py
- lib/wificom/realtime.py
Makes it easier to see what you're doing when connecting the v-pet. I actually thought it was annoying at first but got used to it in a few minutes? Thoughts?
- Blink LED briefly when reporting DigiROM results, like for the Arduino version. "Interesting" results give a slightly longer blink.
> Blink LED when reporting results

- sources.json
Updated dmcomm-python to v0.7.0:
- Finalized Data Link - removed "!" - bytes are reversed from "!" version
- Finalized Fusion Loader - removed "!!" with no changes
- Added calculation features in sequence DigiROMs
> Update dmcomm-python to v0.7.0

- sources.json
- Adds CircuitPython recommended source url to sources.json, currently only used for the update tool
> Add CircuitPython versions to sources.json

- sources.json
- Use CircuitPython version only, not url, in sources.json
> Use CircuitPython version only, in sources.json

- lib/wificom/main.py
- lib/wificom/realtime.py
* Real-time battle improvements:
* Retry final connection
* LED blink for final connection
* Stale messages expire
* Players no longer need to press simultaneously for Legendz
> RTB improvements

- lib/wificom/main.py
- lib/wificom/ui.py
- Play sound when completing startup and reaching main menu.
- Play sound when WiFi/MQTT is ready to receive DigiROMs from the server.
> Play sound when main menu or WiFi is ready

- boot.py
- boot.py now reads button and LED pins from board_config
> Get boot.py pins from board_config

- README.md
- Updated README.md credits to reflect current project contributions
> Update credits for current contribution state

- lib/wificom/main.py
* "Drive Mode" now officially named
* Various other UI text updated
* Removed "Drive" option from Dev Mode menu
(Changed "change" to "exit" on WiFi and Serial but not Punchbag, because "change" makes sense on Punchbag.)
> Update UI text; remove "Drive" from Dev menu

- boot.py
- lib/wificom/main.py
* Stop using data serial
* Stop rebooting between modes (except drive)
> Stop using data serial

- .github/workflows/merge-libs-compile-circuitpython-files.yml
- lib/wificom/main.py
- version_info.py
- New file version_info.py with version info from build CI
- "i" version info command on serial
> Add version info from build, and serial output

- boot.py
- lib/wificom/main.py
- lib/wificom/modes.py
- Use SleepMemory instead of NVM for rebooting
- Request drive eject for fresh installs
> Use SleepMemory instead of NVM for rebooting

- lib/wificom/main.py
- Serial digiroms now work reliably with CR terminator as well as LF - fixes w0rld Android
- No longer crashes from character decoding errors on serial
> Use custom serial readline

- lib/wificom/main.py
We don't need it any more after #130.
* Don't send serial data when no app is connected (resolves serial data echo on Linux)
> Remove serial_print

- lib/wificom/main.py
- version_info.py
* Move Drive into Settings
* Remove menus from Drive and Unknown (hold C to reboot instead); this lets us delete a lot of code
* Add "WiFiCom: " to version info displayed on screen if there is room
* Minor text changes
> Move Drive into Settings; remove Drive menu

- lib/wificom/main.py
- lib/wificom/ui.py
Moved `led` into `ui`. No change in behaviour but makes the code easier to read.
> Refactor LED code

- lib/wificom/main.py
Also reduced hold time to 2 seconds.
> Add button release check to drive

- lib/wificom/ui.py
~~I think the text is too small... would need custom fonts to change this.~~ Surveyed the group and decided it's OK.
Also stopped using `display.show` which will be removed in CircuitPython 9.
> Use native screen resolution

- lib/wificom/main.py
Different beeps for results containing "Error" and "r:".
> Play sounds on "interesting" results

- lib/wificom/main.py
It does seem to line up pretty well with the drive appearing on the computer.
> Beep when drive mode is ready

- config.py
- lib/wificom/main.py
- lib/wificom/settings.py
Save settings back into the file rather than using NVM.
> Change config.py to json

- digiroms.txt
- lib/wificom/ui.py
Compact text lines slightly
Randomise text y-coordinate at startup to help avoid screen burn #194
Menu now only renders visible lines (fixes 6 limit on punchbag)
> Randomise text y-coordinate

- lib/wificom/main.py
> Restore error message for display failure

- .github/workflows/merge-libs-compile-circuitpython-files.yml
`adafruit_connection_manager` required for new minimqtt
> Restore missing lib
