.github/workflows/merge-libs-from-remote.yml
CHANGELOG.md
README.md
sources.json

Brings in automated library bundling for our platform to run.  With this change users will download a wificom-lib_$(RELEASE TAG) archive to copy+paste.  This leaves only the "secrets.py" to be added afterwards.
- See artifacts for a sample run of this action
- Licenses are handled via a new file "LICENSE" with the three lib sources accounted for

Issue #46 - Asset bundling using GitHub Action

---

CHANGELOG.md
code.py

I was thinking something like this, but it turns out there's a bigger problem, and reboots into WiFi mode aren't working on PicoW at all (including the usual case of switching from other modes).
```
Traceback (most recent call last):
File "code.py", line 371, in <module>
File "code.py", line 189, in run_wifi
File "/lib/wificom/wifi_picow.py", line 35, in connect
ConnectionError: Unknown failure 205
```

Reboot if WiFi was run before

---

.github/workflows/merge-libs-compile-circuitpython-files.yml
CHANGELOG.md

- Compiles files in lib/ to mpy (wificom, dmcomm-python, the rest are already compiled)
- Skips compiling empty *.py files to save space

Compile libs to mpy

---

CHANGELOG.md
README.md
code.py
lib/wificom/import_secrets.py
lib/wificom/ui.py
lib/wificom/wifi_nina.py
lib/wificom/wifi_picow.py
secrets.example.py
secrets.py.example

- Modifies the default secrets.py file to use an array of wifi networks
- The list goes from top to bottom when attempting to connect
- Screenless units are accounted for
**Wireless Network Feedback**
- Screened unit, beeps 3x on failure, then displays "WiFi Failed\nHold C to reboot", LED goes out.  Holding C for ~3s will reboot the unit using a reload
- Screenless/speakerless unit, LED goes out, need to reboot to retry
Resolves #57

Multiple wifi networks and retries

---

.github/workflows/pylint.yml

**Description**
Lock pylint to v2.16.2 to maintain compatibility with our existing defined linting rules.
**CHANGELOG**
- Pylint now locked to v2.16.2 when processed by GItHub Actions

Lock pylint to v2.16.2 in Github Action

---

.github/workflows/merge-libs-compile-circuitpython-files.yml
lib/wificom/wifi_picow.py
sources.json

**Description**
I was testing CircuitPython 8.0.4 and found 5.5.1 of MiniMQTT to be incompatible on PicoW but compatible on Nina (running CircuitPython 8.0.4).  I also found out that the latest version of MIniMQTT is very fast in comparison to 5.5.1 (7.3.2).  The connection takes milliseconds on 7.3.2 MiniMQTT instead of seconds.
As a result of my findings I decided to update the GitHub Action to include a matrix for builds for both platforms.  With these builds we can safely go up to CircuitPython 8.0.4 without issues and with the same codebase.
See Artifacts on the last successful build for an example:
- Separate builds for nina and picow microcontrollers with the ability to use variants for MIniMQTT dependency. Will show up as two archives, one endeing in _nina.zip and other in …

GitHub Actions:  MiniMQTT Nina/PicoW Variants

---

lib/wificom/wifi_picow.py

Flagged by newer pylint as `inconsistent-return-statements` but that wasn't quite it.
The diff is weird because the `else: retries -= 1` is in there at two different indentation levels, but I actually just unindented the whole block. Looks more similar to Nina now.
Internal change, no release notes needed.

Remove useless while loop in Pico W wifi

---

lib/wificom/main.py

Unlike dmcomm-python it only appears in `serial_print`, so just changed it there.
- For messages which can appear in serial mode, changed ending of output lines from "\n" to "\r\n" to match Arduino

Make serial line ending CRLF to match Arduino

---

lib/wificom/main.py

Originally I called this "Disable auto-reload in drive mode", but since all other modes have CIRCUITPY read-only, this way is simpler.
- Disabled auto-reload on CIRCUITPY change, except in dev mode

Disable auto-reload when not in dev mode

---

lib/wificom/main.py

- Beep once and blink LED 3 times when a new DigiROM or real-time battle setup request is received over WiFi. (Previously just beeped once on new DigiROM.)

Blink LED for new DigiROM

---

lib/wificom/import_secrets.py

- No longer crashes when secrets.py wireless network list has the wrong structure.

Validate wireless_networks in import_secrets

---

lib/wificom/main.py
lib/wificom/ui.py

- Unexpected exceptions are caught and tracebacks logged to `wificom_log.txt` in CIRCUITPY. File rotated to `wificom_log_old.txt` according to size. Reboot made easier after a crash.
- Reboot after failure waits for short A press instead of holding C.

Log crash tracebacks to file

---

lib/wificom/main.py

- Command and receive errors reported to server via MQTT.
- Error beep on bad command for WiFi and serial.
- New DigiROM alert (beep and triple blink) on serial - combine with note for #93 .

Report errors via MQTT

---

lib/wificom/import_secrets.py
lib/wificom/main.py
lib/wificom/ui.py

- Short LED blink every 2 seconds when failure is reported
- Screenless units can reboot by pressing the button when failure is reported
- Beep on press-to-reboot after failure
- Use failure alert feature for secrets.py errors
- Rotate crash log before writing it to avoid having only "_old" (don't need to mention in final changelog)

Add screenless button use + failure LED blink

---

board_config.py
boot.py
lib/wificom/main.py

- Support for non-WiFi boards (with board_config entries for Pico and Xiao P-Coms) - button held on startup enters Dev Mode
- Drive Mode no longer remembered when unplugged
- board_config entry for Pico WiFiCom with AirLift
Rewrote board_config. Old board_config still works. Boards are allowed to not have WiFi. Refactored menu code. So far, tested PicoW with old board_config, new board_config, and setting WifiCls to None. Need to test more boards, more toys, screenless, and dmcomm-python with this board_config. I didn't really want to add a speaker pin to the Xiao, but making that optional would be a major change and create additional testing burden.

Allow non-WiFi

---

lib/wificom/main.py

* Connection lost improvements:
* When connection is lost, shows a specific error message on screen
* Press B to reconnect after connection lost or WiFi/MQTT failed to connect; press A for menu as before
* Dev mode unchanged
* On screenless units, press the button to restart after crash or connection loss
* Soft reboot instead of hard when running WiFi a second time (faster and doesn't drop serial)
I suggest using a phone hotspot for testing. Can have it turned off to start with for failure to connect to WiFi, or turn it off later for WiFi dropped.

Distinguish "crashed" and "connection lost"

---

.github/workflows/merge-libs-compile-circuitpython-files.yml

Match `mpy-cross` to CircuitPython version (to prepare for testing CircuitPython 9)

Match mpy-cross to CircuitPython version

---

sources.json

Updated Adafruit libs to 2023-11-21 and MiniMQTT to 7.4.4 on both "picow" and "nina". Nina issues seem resolved. From what they were saying, `esp32spi` got updated to behave more similarly to the `wifi` module.

Update Adafruit libs

---

lib/wificom/main.py
lib/wificom/mqtt.py

Added two structs to avoid the messy amount of writing to globals. Also removed the try/except on unsubscribe, I don't *think* we need it there when most of the other operations are unchecked?

Remove globals from MQTT

---

lib/wificom/mqtt.py
lib/wificom/wifi_nina.py
lib/wificom/wifi_picow.py

The minimqtt update changed retry behaviour so that ours was excessive.
For me, keep_alive=15 is detecting hotspot turned off after about 25-30 seconds on PicoW and somewhat less on Nina (Nina was detecting it much quicker before anyway so must also have some other way).

Reduce MQTT timeout and connection attempts

---

lib/wificom/main.py
lib/wificom/mqtt.py
lib/wificom/version.py

I can't see what's happening on the server so can you check that?
As part of this, refactored the version info that shows on the screen or is a result of "i" (wifi or serial).
Dropping "variant" from reported info - picow/nina bundles are going to be identical in the upcoming release, and dropping nina after.
Adding "has_display" to reported info for future server decisions.

Send version info with result / heartbeat

---

boot.py

Hold button for Dev Mode on both wificom and P-Com.
Previously the 3rd state was needed for serial on screenless wificoms, but as of #183 those are no longer supported, so wificom and P-Com can now have the same behaviour.

Reduce boot.py to 2 states

---

.pylintrc
lib/wificom/main.py
lib/wificom/realtime.py
lib/wificom/settings.py
lib/wificom/status.py
lib/wificom/ui.py
lib/wificom/version.py
lib/wificom/wifi_picow.py

New config settings "turn_1_delay" (float) and "turn_1_delay_options" (list of floats). Positive number is time in seconds between new turn-1 digirom received and first transmission, though serial mode keeps a minimum of 1. Negative number means wait for button press of A or B on wificom (button C on P-Com). "turn_1_delay" is settable via settings menu using the list from "turn_1_delay_options". "turn_1_button" (bool) added to info TOML. When on wifi, LED turns off during mqtt loop to indicated wificom unresponsive.

Configure start timing for turn 1 digiroms
